services:
  arobases_sylius_rights_management_plugin.form.type.admin.role:
    class: Arobases\SyliusRightsManagementPlugin\Form\Type\Admin\RoleType
    tags:
      - { name: form.type }

  arobases_sylius_rights_management_plugin.form.type.admin.right_choice:
    class: Arobases\SyliusRightsManagementPlugin\Form\Type\Admin\RightChoiceType
    arguments:
      - '@arobases_sylius_rights_management_plugin.repository.right'
    tags:
      - { name: form.type}

  arobases_sylius_rights_management_plugin.form.type.admin.role_choice:
    class: Arobases\SyliusRightsManagementPlugin\Form\Type\Admin\RoleChoiceType
    arguments:
      - '@arobases_sylius_rights_management_plugin.repository.role'
    tags:
      - { name: form.type}

  arobases_sylius_rights_management_plugin.form.admin_user:
    class: Arobases\SyliusRightsManagementPlugin\Form\Extension\AdminUserTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\User\AdminUserType }

  arobases_sylius_rights_management_plugin.twig_extension.format_right_array:
    class: Arobases\SyliusRightsManagementPlugin\Twig\Extensions\FormatRightArrayExtension
    public: false
    tags:
        - { name: twig.extension }

  arobases_sylius_rights_management_plugin.checker.admin_route_checker:
    class: Arobases\SyliusRightsManagementPlugin\Access\Checker\AdminRouteChecker

  arobases_sylius_rights_management_plugin.checker.admin_user_access_checker:
    class: Arobases\SyliusRightsManagementPlugin\Access\Checker\AdminUserAccessChecker
    arguments:
      - '@Symfony\Component\Routing\RouterInterface'

  arobases_sylius_rights_management_plugin.adapter.right_adapter:
    class: Arobases\SyliusRightsManagementPlugin\Adapter\RightAdapter
    arguments:
      - '@service_container'

  arobases_sylius_rights_management_plugin.command.create_admin_right:
    class: Arobases\SyliusRightsManagementPlugin\Command\CreateAdminRightCommand
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@arobases_sylius_rights_management_plugin.adapter.right_adapter'
      - '@arobases_sylius_rights_management_plugin.repository.right_group'
      - '@arobases_sylius_rights_management_plugin.repository.right'
    tags:
      - { name: console.command }

  arobases_sylius_rights_management_plugin.provider.current_admin_user_provider:
    class: Arobases\SyliusRightsManagementPlugin\Provider\CurrentAdminUserProvider
    arguments:
      - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'

  arobases_sylius_rights_management_plugin.listener.access_check_listener:
    class: Arobases\SyliusRightsManagementPlugin\Access\Listener\AccessCheckListener
    arguments:
      - '@arobases_sylius_rights_management_plugin.provider.current_admin_user_provider'
      - '@arobases_sylius_rights_management_plugin.checker.admin_user_access_checker'
      - '@arobases_sylius_rights_management_plugin.checker.admin_route_checker'
      - '@session'
      - '@Symfony\Component\Routing\RouterInterface'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
      
  arobases_sylius_rights_management_plugin.listener.admin_menu:
    class: Arobases\SyliusRightsManagementPlugin\Menu\AdminMenuListener
    arguments:
      - '@arobases_sylius_rights_management_plugin.checker.admin_user_access_checker'
      - '@arobases_sylius_rights_management_plugin.provider.current_admin_user_provider'
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
